package fitparser

import (
	"strconv"
	"strings"

	"github.com/muktihari/fit/profile/basetype"
	"github.com/muktihari/fit/profile/typedef"
)

// fitEnum is a FIT profile enum type as generated by the upstream profile
// package: an unsigned integer with a String method that returns the FIT
// profile name, or "<Type>Invalid(<n>)" for values the profile does not
// define.
type fitEnum interface {
	~uint8 | ~uint16 | ~uint32
	String() string
}

// enumName converts a FIT enum value into its profile name. The invalid
// sentinel becomes "". A value the profile does not define becomes
// "<snake>_<n>", e.g. "sport_42".
func enumName[T fitEnum](v, invalid T, snake string) string {
	if v == invalid {
		return ""
	}
	s := v.String()
	if s == "" || strings.Contains(s, "Invalid(") {
		return snake + "_" + strconv.FormatUint(uint64(v), 10)
	}
	return s
}

func sportName(v typedef.Sport) string {
	return enumName(v, typedef.SportInvalid, "sport")
}

func subSportName(v typedef.SubSport) string {
	return enumName(v, typedef.SubSportInvalid, "sub_sport")
}

func lapTriggerName(v typedef.LapTrigger) string {
	return enumName(v, typedef.LapTriggerInvalid, "lap_trigger")
}

func eventName(v typedef.Event) string {
	return enumName(v, typedef.EventInvalid, "event")
}

func eventTypeName(v typedef.EventType) string {
	return enumName(v, typedef.EventTypeInvalid, "event_type")
}

func swimStrokeName(v typedef.SwimStroke) string {
	return enumName(v, typedef.SwimStrokeInvalid, "swim_stroke")
}

func splitTypeName(v typedef.SplitType) string {
	return enumName(v, typedef.SplitTypeInvalid, "split_type")
}

func intensityName(v typedef.Intensity) string {
	return enumName(v, typedef.IntensityInvalid, "intensity")
}

func durationTypeName(v typedef.WktStepDuration) string {
	return enumName(v, typedef.WktStepDurationInvalid, "wkt_step_duration")
}

func targetTypeName(v typedef.WktStepTarget) string {
	return enumName(v, typedef.WktStepTargetInvalid, "wkt_step_target")
}

func hrCalcTypeName(v typedef.HrZoneCalc) string {
	return enumName(v, typedef.HrZoneCalcInvalid, "hr_zone_calc")
}

func pwrCalcTypeName(v typedef.PwrZoneCalc) string {
	return enumName(v, typedef.PwrZoneCalcInvalid, "pwr_zone_calc")
}

func manufacturerName(v typedef.Manufacturer) string {
	return enumName(v, typedef.ManufacturerInvalid, "manufacturer")
}

func fileTypeName(v typedef.File) string {
	return enumName(v, typedef.FileInvalid, "file")
}

func mesgNumName(v typedef.MesgNum) string {
	return enumName(v, typedef.MesgNumInvalid, "mesg_num")
}

// productName resolves a device's product name: the free-form product_name
// string when set, otherwise the product profile name that the upstream
// GetProduct selects for the manufacturer (garmin_product for Garmin,
// Dynastream, Dynastream OEM and Tacx; favero_product for Favero), otherwise
// "".
func productName(name string, product uint16, getProduct func() (string, any)) string {
	if name != "" {
		return name
	}
	if product == basetype.Uint16Invalid {
		return ""
	}
	kind, v := getProduct()
	switch p := v.(type) {
	case typedef.GarminProduct:
		return enumName(p, typedef.GarminProductInvalid, kind)
	case typedef.FaveroProduct:
		return enumName(p, typedef.FaveroProductInvalid, kind)
	}
	return ""
}
